[book]
authors = ["Thomas Graves"]
language = "en"
multilingual = false
src = "src"
title = "Pretty Good Software Engineer"

[output.html]
theme = "src/theme"
default-theme = "coal"
additional-js = ["roassal.js"]
mathjax-support = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
